### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by DMJC** [hackcraft-de/linwarrior#3] opened 2018-04-30 13:05 UTC
Logging code error:

c++ -Wp,-M,-MP,-MT,build/source/de/hackcraft/world/sub/cityscape/rBuilding.o,-MF,dep/build-source-de-hackcraft-world-sub-cityscape-rBuilding.o.d -std=gnu++11 -Wall -I source -O1 -funroll-loops -c source/de/hackcraft/world/sub/cityscape/rBuilding.cpp -o build/source/de/hackcraft/world/sub/cityscape/rBuilding.o
In file included from source/de/hackcraft/log/Logger.h:16:0,
                 from source/de/hackcraft/world/sub/cityscape/rBuilding.cpp:6:
source/de/hackcraft/log/LevelStreamLogger.h: In instantiation of ‘LevelStreamLogger& LevelStreamLogger::operator<<(const T&) [with T = std::__cxx11::basic_stringstream<char>]’:
source/de/hackcraft/world/sub/cityscape/rBuilding.cpp:298:32:   required from here
source/de/hackcraft/log/LevelStreamLogger.h:44:19: error: no match for ‘operator<<’ (operand types are ‘std::stringstream {aka std::__cxx11::basic_stringstream<char>}’ and ‘const std::__cxx11::basic_stringstream<char>’)
         logstream << val;
         ~~~~~~~~~~^~~~~~
In file included from /usr/include/c++/6/istream:39:0,
                 from /usr/include/c++/6/sstream:38,
                 from source/de/hackcraft/log/LevelStreamLogger.h:15,
                 from source/de/hackcraft/log/Logger.h:16,
                 from source/de/hackcraft/world/sub/cityscape/rBuilding.cpp:6:
/usr/include/c++/6/ostream:628:5: note: candidate: std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&&, const _Tp&) [with _CharT = char; _Traits = std::char_traits<char>; _Tp = std::__cxx11::basic_stringstream<char>] <near match>
     operator<<(basic_ostream<_CharT, _Traits>&& __os, const _Tp& __x)
     ^~~~~~~~
/usr/include/c++/6/ostream:628:5: note:   conversion of argument 1 would be ill-formed:
In file included from source/de/hackcraft/log/Logger.h:16:0,
                 from source/de/hackcraft/world/sub/cityscape/rBuilding.cpp:6:
source/de/hackcraft/log/LevelStreamLogger.h:44:9: error: cannot bind ‘std::basic_ostream<char>’ lvalue to ‘std::basic_ostream<char>&&’
         logstream << val;
         ^~~~~~~~~
source/de/hackcraft/log/LevelStreamLogger.h:44:19: note: candidate: operator<<(int, int) <built-in>
         logstream << val;
         ~~~~~~~~~~^~~~~~
source/de/hackcraft/log/LevelStreamLogger.h:44:19: note:   no known conversion for argument 2 from ‘const std::__cxx11::basic_stringstream<char>’ to ‘int’
In file included from /usr/include/c++/6/istream:39:0,
                 from /usr/include/c++/6/sstream:38,
                 from source/de/hackcraft/log/LevelStreamLogger.h:15,
                 from source/de/hackcraft/log/Logger.h:16,
                 from source/de/hackcraft/world/sub/cityscape/rBuilding.cpp:6:
/usr/include/c++/6/ostream:108:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_ostream<_CharT, _Traits>::__ostream_type& (*)(std::basic_ostream<_CharT, _Traits>::__ostream_type&)) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(__ostream_type& (*__pf)(__ostream_type&))
       ^~~~~~~~

**Comment by DMJC** [comment] 2018-04-30 16:33
Issue is occurring on Debian Linux AMD64.

**Comment by DMJC** [comment] 2018-05-07 07:37
I've been able to hack around this but I'd advise someone who knows what they're doing look at the patch.

    template<typename T>
	#ifdef __linux__
    LevelStreamLogger& operator<<(const T& val) {
        logstream << &val;
	#else
    LevelStreamLogger& operator<<(T const& val) {
        logstream << val;
	#endif
        appendStream();
        return *this;
    }

**Comment by hackcraft-de** [comment] 2018-05-09 12:44
Thank you James, I'll just reopen this issue for me until I get to test your fix and resolve it in the repository.

**Comment by hackcraft-de** [comment] 2018-05-10 21:09
Ok, I've tested this on my linux. Just switching the "const" is enough. With the extra "&" it will compile but logging wont work anymore. I've added the const-switch to the plus-operator as well and will commit the fix.

Please be sure to pull the latest version because I've fixed a critical bug in the shaders as well.

**Comment by hackcraft-de** [comment] 2018-05-10 21:12
By the way could you please provide the output of "c++ --version" on your system?

Thank you in advance.

**Comment by DMJC** [comment] 2018-05-10 22:51
c++ (Debian 7.3.0-17) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by hackcraft-de** [comment] 2018-05-11 06:42
Ok, my version is far older (4.8.4).

Could you please try if replacing "&val" with either "*&val" or "(*(&val))" compiles for you and produces any log outputs like:
 .. INFO de.hackcraft.game.GameMain - ...

**Comment by hackcraft-de** [comment] 2018-05-11 06:44
There should be a asterisk/star * before the & above. Github formatting deleted that. So it should be either:
"starsign andsign val"
"(starsign (andsign val))"

**Comment by hackcraft-de** [comment] 2018-06-23 12:14
Aforementioned fix may or may not fix the problem with newer compilers.
The problem is not reproducable on my setup and the opener doesn't reply.
Best effort done - closing this for now.

**Closed by hackcraft-de** 2018-06-23 12:14 UTC

**Comment by qubodup** [comment] 2019-07-18 23:07
I got a bit confused by the instructions. In my case, the code already looked the way I think the instruction was to make it look.

To format code in github use the
![image](https://user-images.githubusercontent.com/18312/61495457-5fa1e480-a9b9-11e9-873a-aaeb66a043b6.png) `<>` button or type ` before and after the code (or ``` for multiline).
